name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change the rust version to nightly
        working-directory: ./server
        run: rustup default nightly

      - name: Build
        working-directory: ./server
        run: cargo build --verbose

      - name: Run tests
        working-directory: ./server
        run: cargo test --verbose
